---
# Source: helm-chart-templates/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
  namespace: payment
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: "cuongdangdevsecops/payment-service:6.0.2"
          resources:
            limits:
              cpu: 600M
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          ports:
              - containerPort: 8080
