---
# Source: helm-chart-templates/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment
  labels:
    app: payment-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: payment-service
