---
# Source: helm-chart-templates/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: inventory
  labels:
    app: inventory-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: inventory-service
