---
# Source: helm-chart-templates/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: notification
  labels:
    app: notification-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: notification-service
