---
# Source: helm-chart-templates/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: shipment-service
  namespace: shipment
  labels:
    app: shipment-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: shipment-service
